- deploy/arm/infrastructure.json
- deploy/arm/infrastructure.parameters.json
- src/new-notice-notifications/README.md
- src/notice-expiry/README.md
- src/notice-reminders/README.md
- src/shared/service-bus-queue-to-event-grid.json
- src/shared/service-bus-queue-to-event-grid.parameters.json
Provide basic infrastructure:
- Basic structure in source repo for all our processes
- ARM template to create the shared infrastructure
- Event Grid Topic
- Service Bus namespace
- ARM template to deploy a process to drain a queue and post it as an event to Event Grid
Closes #6
```json
{
"data": {
"foo": "bar"
},
"eventType": "SampleEventType",
"id": "19eb4fb0-8bb7-4eb6-96c1-b9c0cf5f7037",
"subject": "/"
}
```
> Provide basic infrastructure

- src/AzureDeprecation.Contracts/AzureDeprecation.Contracts.csproj
- src/AzureDeprecation.Integrations.GitHub/AzureDeprecation.Integrations.GitHub.csproj
- src/AzureDeprecation.Integrations.GitHub/Repositories/GitHubRepository.cs
- src/AzureDeprecation.Notices.Management/AzureDeprecation.Notices.Management.csproj
- src/AzureDeprecation.Notices.Management/MessageHandlers/NewAzureDeprecationV1MessageMessageHandler.cs
- src/AzureDeprecation.Notifications/AzureDeprecation.Notifications.csproj
Automatically lock issue and use GitHub Discussions
Closes #23
> Automatically lock issue and use GitHub Discussions

- src/AzureDeprecation.Integrations.GitHub/Repositories/GitHubRepository.cs
- src/AzureDeprecation.Notices.Management/MessageHandlers/NewAzureDeprecationV1MessageMessageHandler.cs
> Automatically add new notices to our deprecation dashboard project

- src/AzureDeprecation.Contracts/Enum/ContactType.cs
- src/AzureDeprecation.Contracts/Messages/v1/ContactEntry.cs
- src/AzureDeprecation.Contracts/Messages/v1/DeprecationInfo.cs
- src/AzureDeprecation.Contracts/Messages/v1/NewAzureDeprecationV1Message.cs
- src/AzureDeprecation.Notices.Management/IssueFactory.cs
- src/AzureDeprecation.Tests.Unit/AutoMapperTests.cs
- src/AzureDeprecation.Tests.Unit/Generator/NewAzureDeprecationGenerator.cs
- src/AzureDeprecation.Tests.Unit/IssueFactoryTests.cs
> Provide support for multiple support options

- src/AzureDeprecation.Contracts/Enum/AzureCloud.cs
- src/AzureDeprecation.Contracts/Enum/AzureService.cs
- src/AzureDeprecation.Notices.Management/IssueFactory.cs
- src/AzureDeprecation.Notices.Management/LabelFactory.cs
- src/AzureDeprecation.Notices.Management/MessageHandlers/NewAzureDeprecationV1MessageMessageHandler.cs
- src/AzureDeprecation.Notices.Management/Startup.cs
> Support more clouds & Azure Application Insights

- .github/workflows/ci.yml
- deploy/azure-infrastructure.json
- deploy/azure-infrastructure.parameters.ci.json
- deploy/azure-infrastructure.parameters.json
> feat: Provide ARM template for Azure infrastructure

- .github/workflows/deploy-azure-infrastructure.yml
- .github/workflows/package-azure-infrastructure.yml
> feat: Provide automated deployment for Azure infrastructure to staging

- .github/workflows/package-azure-infrastructure.yml
> fix: Provide working Azure infrastructure package & deploy

- deploy/azure-infrastructure.json
- deploy/azure-infrastructure.parameters.ci.json
Provide working ARM template for shared Azure infrastructure
> fix: Provide working ARM template for shared Azure infrastructure

- .github/workflows/ci.yml
- deploy/azure-infrastructure.json
- deploy/azure-infrastructure.parameters.ci.json
- deploy/azure-infrastructure.parameters.json
- deploy/notice-management.json
- deploy/notice-management.parameters.ci.json
- deploy/notice-management.parameters.json
> feat: Provide ARM template for Azure Function (Notice Management)

- .github/workflows/deploy-azure-infrastructure.yml
- .github/workflows/package-azure-infrastructure.yml
> fix: Fix broken Azure Infrastructure package

- .github/workflows/deploy-azure-infrastructure.yml
- .github/workflows/deploy-notice-management.yml
- .github/workflows/package-notice-management.yml
- deploy/notice-management.parameters.staging.json
> feat: Provide first rough version of deployment pipeline for Notice Management

- .github/workflows/deploy-notice-management.yml
- deploy/notice-management.parameters.production.json
> feat: Provide functional Notice Management deployment pipeline

- deploy/notice-management.json
- deploy/notifications.json
- deploy/notifications.parameters.json
- deploy/notifications.parameters.production.json
- deploy/notifications.parameters.staging.json
> fix: Use correct API connections for tweet workflow

- .github/workflows/ci.yml
> fix: Add missing parameters in CI

- deploy/notifications.json
> feat: Show composed new / upcoming deprecations

- src/AzureDeprecation.Notices.Management/MessageHandlers/NewAzureDeprecationV1MessageMessageHandler.cs
- src/AzureDeprecation.Runtimes.AzureFunctions/Startup.cs
- Make application insights sink optional
- Make date parsing culture independent
> fix: Minor improvements to local execution of Notice Management

- .github/workflows/ci.yml
> feat(ci): Use OpenID Connect to authenticate to Azure

- src/AzureDeprecation.Notices.Management/IssueFactory.cs
> fix: Provide proper contact info when none is available

- .github/workflows/deploy-azure-infrastructure.yml
- .github/workflows/deploy-notice-management.yml
- .github/workflows/deploy-notifications.yml
> feat: Use OpenID Connect to authenticate to Azure for deployments

- .github/workflows/deploy-notice-management.yml
Use official ARM deployment step which now supports passing parameters outside of JSON files
> feat(notice-management): Use official ARM deployment step

- deploy/notice-management.json
- deploy/notifications.json
- global.json
- src/AzureDeprecation.Contracts/AzureDeprecation.Contracts.csproj
- src/AzureDeprecation.Integrations.GitHub/AzureDeprecation.Integrations.GitHub.csproj
- src/AzureDeprecation.Integrations.GitHub/Repositories/GitHubRepository.cs
- src/AzureDeprecation.Notices.Management/AzureDeprecation.Notices.Management.csproj
- src/AzureDeprecation.Notices.Management/Functions/NewAzureDeprecationNotificationFunction.cs
- src/AzureDeprecation.Notices.Management/MessageHandlers/ServiceBusMessageHandler.cs
- src/AzureDeprecation.Notices.Management/Properties/ServiceDependencies/azure-deprecation-notice-management - Zip Deploy/profile.arm.json
- src/AzureDeprecation.Notifications/AzureDeprecation.Notifications.csproj
- src/AzureDeprecation.Notifications/Properties/ServiceDependencies/azure-deprecation-notifications - Zip Deploy/profile.arm.json
- src/AzureDeprecation.Runtimes.AzureFunctions/AzureDeprecation.Runtimes.AzureFunctions.csproj
- src/AzureDeprecation.Tests.Unit/AzureDeprecation.Tests.Unit.csproj
- src/AzureDeprecation.Tests.Unit/IssueFactoryTests.cs
- src/AzureDeprecation.sln
- src/Directory.Packages.props
- Upgrade to .NET 6 #66;
- Upgrade Nugets #93;
- Update ARM templates for Azure Functions v4
> feat: Upgrade to .NET 6, Azure Functions v4 and latest dependencies

- src/AzureDeprecation.APIs.REST/host.json
> fix(rest-api): Don't use default route prefix

- src/AzureDeprecation.APIs.REST/Contracts/ServiceException.cs
- src/AzureDeprecation.APIs.REST/DataAccess/Interfaces/IDeprecationsRepository.cs
- src/AzureDeprecation.APIs.REST/DataAccess/Repositories/CosmosDbDeprecationsRepository.cs
- src/AzureDeprecation.APIs.REST/Functions/GetDeprecationFunction.cs
Relates to https://github.com/azure-deprecation/infrastructure/issues/72
> Provide REST API endpoint to get deprecation details

- openapi.json
- src/AzureDeprecation.APIs.REST/AzureDeprecation.APIs.REST.csproj
- src/AzureDeprecation.APIs.REST/Extensions/IServiceCollectionExtensions.cs
- src/AzureDeprecation.APIs.REST/Functions/GetDeprecationFunction.cs
- src/AzureDeprecation.APIs.REST/Functions/GetDeprecationsFunction.cs
- src/AzureDeprecation.APIs.REST/Startup.cs
- src/AzureDeprecation.Integrations.Azure.CosmosDb/Extensions/IServiceCollectionExtensions.cs
- src/Directory.Packages.props
> feat(rest-api): Provide OpenAPI specs

- deploy/azure-infrastructure.bicep
- deploy/azure-infrastructure.parameters.json
- deploy/azure-infrastructure.parameters.production.json
- deploy/azure-infrastructure.parameters.staging.json
- deploy/rest-api.bicep
- deploy/rest-api.parameters.json
- deploy/rest-api.parameters.production.json
- deploy/rest-api.parameters.staging.json
> feat(api-gateway): Automatically deploy Azure API Management

- deploy/rest-api.bicep
> feat: Automatically authenticate requests downstream to Azure Functions

- deploy/azure-infrastructure.bicep
> fix(azure-infra): Ensure Microsoft.ApiManagement/service/diagnostics/loggers waits for logger to be created

- deploy/rest-api.bicep
> fix(rest-api): Ensure APIM APIs are created before adding to product

- deploy/azure-infrastructure.bicep
- deploy/rest-api.bicep
> feat(api-gateway): Introduce "End-User" group for public product

- src/AzureDeprecation.Notices.Management/IssueFactory.cs
- src/AzureDeprecation.Notices.Management/MessageHandlers/NewAzureDeprecationV1MessageMessageHandler.cs
- src/AzureDeprecation.Tests.Unit/IssueFactoryTests.cs
> feat(dashboard): Show unique deprecation ID
